spring.application.name=fabrixa-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/fabrixa_db
spring.datasource.username=postgres
spring.datasource.password=Ceci1998.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=cambiaEstaClaveSecretaPorUnaMuyLargaYAleatoriaDeAlMenos64Caracteres
jwt.expiration-ms=86400000